### ISSUE TITLE
Find solution for updating Attachements in database

### ISSUE THREAD

**Issue by SteffenGorenflo** [locator-kn/ark#13]
Everytime an attachment is added to an existing document, the current revision number of the document must be emitted. (Not only the id) 

There a two solutions:
 1. The client sends the revision number (in addition to the id). In that case, the client needs to know about the number from somewher
 2. The server sends a "little" request to the database in order to get the current revision number to the corresponding id document, before saving the attachment

**Comment by SteffenGorenflo** [comment]
Idea for the second solution: fork flatiron/cradle and implement an update method

**Comment by SteffenGorenflo** [comment]
Next question: What about saving thumbnails? When an additional photo is attached, the current revision must also be retrieved. It seems that it is not possible to stream multiple attachements

**Comment by SteffenGorenflo** [comment]
HEAD request will retrieve a lightweight status of the document (id & rev)

**Comment by T1m1** [comment]
done?

**Comment by SteffenGorenflo** [comment]
almost..

It needs to be discussed, how multiple pictures are saved (in trip e.g.)
