### ISSUE TITLE
couchdb returns with invalid_json for user/_list/listall/user + userid

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/ark#20]
See: http://locator.in.htwg-konstanz.de:5984/app/_design/user/_list/listall/user?key=ed5ad22e5fc3cb76148be1935fe836be

If you don't supply a key, the request works.

**Comment by T1m1** [comment]
Hey Timo,

if you want to use this query string in couchdb directly, you have to quote the key value like:

http://locator.in.htwg-konstanz.de:5984/app/_design/user/_list/listall/user?key="ed5ad22e5fc3cb76148be1935fe836be"

**Comment by timoweiss** [comment]
ok thank, but we are currently running in this issue by using the programmatically approach with cradle. (Logging in with Google -> invalid json, Loggin in with "default" just works)
