### ISSUE TITLE
Add image urls for trips

### ISSUE THREAD

**Issue by timoweiss** [locator-kn/ark#26]
We should provide image urls for the fronted. Not sure how to handle this because the locations could change over time.

**Comment by SteffenGorenflo** [comment]
when creating a trip, provide a hashmap with locations and its pictures

**Comment by SteffenGorenflo** [comment]
now, if a location gets updated (picture or googlemap) all trips got updated too
If a location is requested to delete and this location is in trip, it gets rejected

**Comment by SteffenGorenflo** [comment]
I'm gay :+1:
